name: spotmefitness_ui
description: A fitness platform for the next generation.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: "0.0.1"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  another_flushbar: ^1.10.17
  audio_session: ^0.1.0
  auto_route: ^1.0.1
  better_player: ^0.0.63
  cupertino_icons: ^1.0.2
  custom_pop_up_menu: ^1.2.0
  equatable: ^2.0.0
  email_validator: ^2.0.1
  file_picker: ^3.0.1
  firebase_auth: ^1.0.2
  firebase_core: ^1.0.3
  flutter_slidable: ^0.6.0
  flutter_sound_lite: ^8.1.1
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.21.0
  fullscreen: ^1.0.3
  get_it: ^6.0.0
  google_fonts: ^2.0.0
  graphql_flutter: ^5.0.0-nullsafety.2
  hive: ^2.0.2
  implicitly_animated_reorderable_list: ^0.4.0
  intl: ^0.17.0
  image_picker: ^0.7.4
  image_cropper: ^1.4.0
  json_annotation: ^4.0.1
  just_audio: ^0.7.4
  meta: ^1.3.0
  modal_bottom_sheet: ^2.0.0
  permission_handler: ^6.1.3
  photo_view: ^0.11.1
  provider: ^5.0.0
  simple_animations: ^3.0.1
  timeline_tile: ^2.0.0
  uploadcare_flutter: ^1.0.2

dev_dependencies:
  artemis: 7.0.0-beta.2
  auto_route_generator: ^1.0.1
  build_runner: ^1.11.5
  json_serializable: ^4.1.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.7+1
  flutter_test:
    sdk: flutter
    
flutter_icons:
  android: "spot_me_launcher_icon"
  ios: "spot_me_launcher_icon"
  image_path: "assets/logos/spotme_launcher_icon.png"

flutter_native_splash:
  image: "assets/logos/spotme_splash_icon.png"
  color: "#000000"

flutter:
  assets: 
    - assets/body_areas/
    - assets/body_areas/front/
    - assets/body_areas/front/selection/
    - assets/body_areas/back/
    - assets/body_areas/back/selection/
    - assets/equipment_icons/
    - assets/flags/png/
    - assets/logos/
    - assets/stock_images/

  uses-material-design: true
