name: spotmefitness_ui
description: A fitness platform for the next generation.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: "0.0.1"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  animated_text_kit: ^4.2.1
  another_flushbar: ^1.10.23
  audio_session: ^0.1.5
  auto_route: ^2.2.0
  better_player: ^0.0.70
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.3
  custom_pop_up_menu: ^1.2.0
  equatable: ^2.0.0
  email_validator: ^2.0.1
  file_picker: ^3.0.4
  firebase_auth: ^3.0.1
  firebase_core: ^1.3.0
  # firebase_messaging: ^10.0.5
  flutter_rating_bar: ^4.0.0
  flutter_slidable: ^0.6.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  fullscreen: ^1.0.3
  get_it: ^7.1.4
  google_fonts: ^2.1.0
  gql: ^0.13.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  implicitly_animated_reorderable_list: ^0.4.1
  infinite_scroll_pagination: ^3.0.1+1
  intl: ^0.17.0
  image_picker: ^0.8.0+3
  image_cropper: ^1.4.1
  json_annotation: ^4.0.1
  just_audio: ^0.9.10
  meta: ^1.3.0
  modal_bottom_sheet: ^2.0.0
  normalize: ^0.5.5
  percent_indicator: ^3.0.1
  permission_handler: ^8.1.1
  photo_view: ^0.12.0
  provider: ^5.0.0
  record: ^3.0.0
  rxdart: ^0.27.2
  screenshot: ^1.2.3
  scroll_to_index: ^2.0.0
  share_plus: ^2.1.4
  shimmer: ^2.0.0
  simple_animations: ^3.1.1
  sliding_up_panel: ^2.0.0+1
  stream_chat_flutter: ^2.2.1
  stream_feed: ^0.3.0
  stop_watch_timer: ^1.3.0 # Controller only - no UI. Provides streams and sinks.
  substring_highlight: ^1.0.33
  syncfusion_flutter_charts: ^19.2.60
  table_calendar: ^3.0.0
  timeline_tile: ^2.0.0
  uuid: ^3.0.4
  uploadcare_flutter: ^1.0.2
  url_launcher: ^6.0.10
  uni_links: ^0.5.1

dev_dependencies:
  artemis: ^7.1.1-beta.1
  auto_route_generator: ^2.1.0
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.3
  hive_generator: ^1.1.0
  json_serializable: ^4.1.3
    
flutter_icons:
  # Android
  android: true
  image_path_android: "assets/logos/sofie_launcher_icon_android.png"
  adaptive_icon_background: "#1a1a1c"
  adaptive_icon_foreground: "assets/logos/sofie_launcher_icon_android.png"
  # ios
  ios: true
  image_path_ios: "assets/logos/sofie_launcher_icon_ios.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#1a1a1c"
  image: "assets/logos/sofie_splash_image.png"
  info_plist_files:
    - 'ios/Runner/Info-Debug.plist'
    - 'ios/Runner/Info-Release.plist'

flutter:
  assets: 
    - assets/body_areas/
    - assets/body_areas/front/
    - assets/body_areas/front/selection/
    - assets/body_areas/back/
    - assets/body_areas/back/selection/
    - assets/equipment_icons/
    - assets/flags/png/
    - assets/home_page_images/
    - assets/indicators/
    - assets/logos/
    - assets/other_app_icons/
    - assets/progress_page_images/
    - assets/stock_images/
    - assets/social_images/
    - assets/workout_filters_icons/

  uses-material-design: true