name: spotmefitness_ui
description: A fitness platform for the next generation.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: "0.0.1"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  another_flushbar: ^1.10.22
  audio_session: ^0.1.0
  auto_route: ^2.2.0
  better_player: ^0.0.66
  carousel_slider: ^4.0.0-nullsafety.0
  cupertino_icons: ^1.0.3
  custom_pop_up_menu: ^1.2.0
  equatable: ^2.0.0
  email_validator: ^2.0.1
  file_picker: ^3.0.1
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  flutter_rating_bar: ^4.0.0
  flutter_slidable: ^0.6.0
  flutter_sound_lite: ^8.1.1
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  fullscreen: ^1.0.3
  get_it: ^7.1.3
  google_fonts: ^2.1.0
  gql: ^0.13.0
  graphql: 5.0.0-nullsafety.5
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  implicitly_animated_reorderable_list: ^0.4.0
  infinite_scroll_pagination: ^3.0.1+1
  intl: ^0.17.0
  image_picker: ^0.7.5+2
  image_cropper: ^1.4.0
  json_annotation: ^4.0.1
  just_audio: ^0.7.4+1
  meta: ^1.3.0
  modal_bottom_sheet: ^2.0.0
  percent_indicator: ^3.0.1
  permission_handler: ^7.1.0
  photo_view: ^0.11.1
  provider: ^5.0.0
  rxdart: ^0.26.0
  shimmer: ^2.0.0
  simple_animations: ^3.1.1
  sliding_up_panel: ^2.0.0+1
  substring_highlight: ^1.0.33
  table_calendar: ^3.0.0
  timeline_tile: ^2.0.0
  uuid: ^3.0.4
  uploadcare_flutter: ^1.0.2

dev_dependencies:
  artemis: 7.0.0-beta.11
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.3
  json_serializable: ^4.1.2
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
    
flutter_icons:
  # Android
  android: true
  image_path_android: "assets/logos/spotme_launcher_icon_android.png"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "assets/logos/spotme_launcher_icon_android.png"
  # ios
  ios: true
  image_path_ios: "assets/logos/spotme_launcher_icon_ios.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#191919"
  image: "assets/logos/spotme_splash_image.png"
  info_plist_files:
    - 'ios/Runner/Info-Debug.plist'
    - 'ios/Runner/Info-Release.plist'

flutter:
  assets: 
    - assets/body_areas/
    - assets/body_areas/front/
    - assets/body_areas/front/selection/
    - assets/body_areas/back/
    - assets/body_areas/back/selection/
    - assets/equipment_icons/
    - assets/flags/png/
    - assets/indicators/
    - assets/logos/
    - assets/stock_images/
    - assets/workout_filters_icons/

  uses-material-design: true
