name: spotmefitness_ui
description: A fitness platform for the next generation.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: "0.0.1"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  auto_route: ^1.0.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  email_validator: 2.0.0-nullsafety
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  flutter_spinkit: ^5.0.0
  flutter_svg: 0.21.0-nullsafety.0
  get_it: ^6.0.0
  google_fonts: ^2.0.0
  graphql_flutter: ^5.0.0-nullsafety.1
  hive: ^2.0.0
  image_picker: ^0.7.3
  image_cropper: ^1.4.0
  intl: ^0.17.0
  json_annotation: ^4.0.0
  meta: ^1.3.0
  modal_bottom_sheet: ^2.0.0
  provider: ^5.0.0
  simple_animations: ^3.0.1
  timeline_tile: ^2.0.0
  uploadcare_flutter: ^1.0.2

dev_dependencies:
  artemis: 7.0.0-beta.1
  auto_route_generator: ^1.0.1
  build_runner: ^1.11.5
  json_serializable: ^4.0.2
  # flutter_launcher_icons: ^0.9.0
  # flutter_native_splash: ^1.0.3
  flutter_test:
    sdk: flutter

# Required until Artemis package sorts its shit out
dependency_overrides:
  build: ^2.0.0
  # analyzer: ^1.0.0
  # equatable: ^2.0.0
  intl: ^0.17.0
  dart_style: ^2.0.0
  glob: ^2.0.0
  gql: ^0.13.0-nullsafety.2
  gql_exec: ^0.3.0-nullsafety.1
  gql_dedupe_link: ^2.0.0-nullsafety.1
  gql_link: ^0.4.0-nullsafety.2
  gql_http_link: ^0.4.0-nullsafety.1
  http: ^0.13.0
  source_gen: ^1.0.0
  # json_annotation: ^4.0.0
  # web_socket_channel: ^2.0.0
  # recase: ^4.0.0-nullsafety.0
  yaml: ^3.1.0
    
# flutter_icons:
#   android: "spot_me_launcher_icon"
#   ios: "spot_me_launcher_icon"
#   image_path: "assets/logos/spotme_launcher_icon.png"

# flutter_native_splash:
#   image: "assets/logos/spotme_splash_icon.png"
#   color: "#000000"

flutter:
  assets: 
    - assets/logos/
    - assets/stock_images/

  uses-material-design: true
