/// Non API Enums (Client only) - Enums from the GQL schema are generated by Artemis.

/// [friend] is 1 - 1. [club] is a group chat for all club members.
enum ChatType { friend, club }

enum TrialType { BASIC, PRO }

enum ToastType { standard, destructive, success }
